/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "CPU": {                                         "en": "CPU",                                             "de": "CPU",                                             "ru": "ЦПУ",                                             "pt": "CPU",                                             "nl": "CPU",                                             "fr": "CPU",                                             "it": "processore",                                      "es": "UPC",                                             "pl": "procesor"},
    "Memory": {                                      "en": "Memory",                                          "de": "Speicher",                                        "ru": "Память",                                          "pt": "Memória",                                         "nl": "Geheugen",                                        "fr": "Mémoire",                                         "it": "Memoria",                                         "es": "Memoria",                                         "pl": "Pamięć"},
    "Network": {                                     "en": "Network",                                         "de": "Netzwerk",                                        "ru": "сеть",                                            "pt": "Rede",                                            "nl": "Netwerk",                                         "fr": "Réseau",                                          "it": "Rete",                                            "es": "Red",                                             "pl": "Sieć"},
    "Swap": {                                        "en": "Swap",                                            "de": "Swap",                                            "ru": "Замена",                                          "pt": "Troca",                                           "nl": "ruil",                                            "fr": "Échanger",                                        "it": "Scambiare",                                       "es": "Intercambiar",                                    "pl": "Zamiana"},
    "Tinker Board-Monitor Adapter settings": {       "en": "Tinker Board-Monitor Adapter settings",           "de": "Tinker-Board-Monitor Adapter Einstellungen",      "ru": "Настройки адаптера Tinker Board-монитора",        "pt": "Configurações do adaptador Tinker Board-Monitor", "nl": "Tinker Board-Monitor Adapterinstellingen",        "fr": "Paramètres de l'adaptateur Tinker Board-Monitor", "it": "Impostazioni dell'adattatore per monitor Tinker Board", "es": "ConfiguraciÃ³n del adaptador Tinker Board Monitor", "pl": "Ustawienia adaptera Tinker Board-Monitor"},
    "Temperature": {                                 "en": "Temperature",                                     "de": "Temperatur",                                      "ru": "температура",                                     "pt": "Temperatura",                                     "nl": "Temperatuur",                                     "fr": "Température",                                     "it": "Temperatura",                                     "es": "Temperatura",                                     "pl": "Temperatura"},
    "Uptime": {                                      "en": "Uptime",                                          "de": "Uptime",                                          "ru": "Uptime",                                          "pt": "Tempo de atividade",                              "nl": "Uptime",                                          "fr": "Uptime",                                          "it": "uptime",                                          "es": "Tiempo de actividad",                             "pl": "Czas pracy"},
    "WLAN": {                                        "en": "WLAN",                                            "de": "WLAN",                                            "ru": "WLAN",                                            "pt": "WLAN",                                            "nl": "WLAN",                                            "fr": "WLAN",                                            "it": "WLAN",                                            "es": "WLAN",                                            "pl": "WLAN"},
    "sdcard": {                                      "en": "SD Card",                                         "de": "SD Karte",                                        "ru": "SD-карта",                                        "pt": "Cartão SD",                                       "nl": "SD-kaart",                                        "fr": "Carte SD",                                        "it": "Scheda SD",                                       "es": "Tarjeta SD",                                      "pl": "Karta SD"},
};